AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM template with a simple API definition
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: HttpApi
        GetWapitLeague:
          Type: HttpApi
          Properties:
            Path: /ncaa/wapit/league/{league_id}/year/{year}
            Method: GET
        PostWapitLeague:
          Type: HttpApi
          Properties:
            Path: /ncaa/wapit/league/{league_id}/year/{year}
            Method: POST
      Handler: handler.handler
      Runtime: python3.10
      CodeUri: src/
      Timeout: 900
Transform: AWS::Serverless-2016-10-31


#Transform: AWS::Serverless-2016-10-31
#
#Description:
#  Vsnandy Lambda API
#
#Resources:
#  VsnandyLambdaApi:
#    Type: AWS::Serverless::Function
#    Properties:
#      Runtime: python3.10
#      Handler: index.handler
#      CodeUri: src/
#      Handler: handler.handler
#      Timeout: 900