name: Deploy AWS CDK

# Controls when the action will run
on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  aws_cdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-role
          role-session-name: session
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # Install your Python dependencies here
          pip install -r ${PWD}/requirements.txt
          npm install -g aws-cdk

      - name: CDK Synth
        run: cdk synth

      - name: Deploy to AWS
        run: cdk deploy --require-approval=never