name: Terraform Destroy

on:
  workflow_dispatch

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
        env:
          TF_VAR_lambda_logging_policy_arn: ${{ secrets.LAMBDA_LOGGING_POLICY_ARN }}
      
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_lambda_logging_policy_arn: ${{ secrets.LAMBDA_LOGGING_POLICY_ARN }}